### ISSUE TITLE
qwen1.5 系列的大模型都支持这个项目吗？

### ISSUE THREAD

**Issue by momomobinx** [QwenLM/Qwen-Agent#104]
如题，是不是qwen1.5 系类都做了示例中的agent提示词对齐，可以稳定规范的返回给定的格式

**Comment by JianxinMa** [comment]
function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。

**Comment by tiejunhu** [comment]
> function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。

我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？

**Comment by JianxinMa** [comment]
> > function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。
> 
> 我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？

是的，都支持。qwen1.5（以及dashscope的qwen-max/plus/turbo) 一般推荐用默认的function calling模版（指examples/function_calling.py那个示例背后用的模版） —— 但这个模版目前也发现了一些已知的问题，比如 code Interpreter 效果相比qwen1的react模版有所下降，容易在没有相关工具时误调用工具等问题。可以先试试1.5的模版，效果不佳就回退用qwen1的模版（react模版）。

**Comment by ye7love7** [comment]
我也发现了1.5工具调用下降的问题。
请问1.5的模板在哪里？

---原始邮件---
发件人: "Jianxin ***@***.***&gt;
发送时间: 2024年3月29日(周五) 晚上9:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104)




   
function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。
  
我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？
  
是的，都支持。qwen1.5（以及dashscope的qwen-max/plus/turbo) 一般推荐用默认的function calling模版（指examples/function_calling.py那个示例背后用的模版） —— 但这个模版目前也发现了一些已知的问题，比如 code Interpreter 效果相比qwen1的react模版有所下降，容易在没有相关工具时误调用工具等问题。可以先试试1.5的模版，效果不佳就回退用qwen1的模版（react模版）。

**Comment by ye7love7** [comment]
我目前用的是本地起的72b模型，用vllm输出标准openai接口



---原始邮件---
发件人: "Jianxin ***@***.***&gt;
发送时间: 2024年3月29日(周五) 晚上9:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104)




   
function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。
  
我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？
  
是的，都支持。qwen1.5（以及dashscope的qwen-max/plus/turbo) 一般推荐用默认的function calling模版（指examples/function_calling.py那个示例背后用的模版） —— 但这个模版目前也发现了一些已知的问题，比如 code Interpreter 效果相比qwen1的react模版有所下降，容易在没有相关工具时误调用工具等问题。可以先试试1.5的模版，效果不佳就回退用qwen1的模版（react模版）。

**Comment by JianxinMa** [comment]
> 我也发现了1.5工具调用下降的问题。 请问1.5的模板在哪里？
> […](#)
> ---原始邮件--- 发件人: "Jianxin ***@***.***&gt; 发送时间: 2024年3月29日(周五) 晚上9:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104) function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。 我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？ 是的，都支持。qwen1.5（以及dashscope的qwen-max/plus/turbo) 一般推荐用默认的function calling模版（指examples/function_calling.py那个示例背后用的模版） —— 但这个模版目前也发现了一些已知的问题，比如 code Interpreter 效果相比qwen1的react模版有所下降，容易在没有相关工具时误调用工具等问题。可以先试试1.5的模版，效果不佳就回退用qwen1的模版（react模版）。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

1.5模版见 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py

**Comment by ye7love7** [comment]
我翻看了一下代码，如果是本地的qwen，用openai接口启动，会对应到oai的llm，这个llm就继承了basetextchatmodel，又继承自basefncallmodel，也就是说本地模型按照openai接口填入模型配置，都有fncall的方法，对吗？



---原始邮件---
发件人: "Jianxin ***@***.***&gt;
发送时间: 2024年3月29日(周五) 晚上9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104)




  
我也发现了1.5工具调用下降的问题。 请问1.5的模板在哪里？
 …
 ---原始邮件--- 发件人: "Jianxin @.&gt; 发送时间: 2024年3月29日(周五) 晚上9:03 收件人: @.&gt;; 抄送: @.&gt;; 主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104) function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。 我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？ 是的，都支持。qwen1.5（以及dashscope的qwen-max/plus/turbo) 一般推荐用默认的function calling模版（指examples/function_calling.py那个示例背后用的模版） —— 但这个模版目前也发现了一些已知的问题，比如 code Interpreter 效果相比qwen1的react模版有所下降，容易在没有相关工具时误调用工具等问题。可以先试试1.5的模版，效果不佳就回退用qwen1的模版（react模版）。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
1.5模版见 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py

**Comment by JianxinMa** [comment]
> 我翻看了一下代码，如果是本地的qwen，用openai接口启动，会对应到oai的llm，这个llm就继承了basetextchatmodel，又继承自basefncallmodel，也就是说本地模型按照openai接口填入模型配置，都有fncall的方法，对吗？
> […](#)
> ---原始邮件--- 发件人: "Jianxin ***@***.***&gt; 发送时间: 2024年3月29日(周五) 晚上9:16 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104) 我也发现了1.5工具调用下降的问题。 请问1.5的模板在哪里？ … ---原始邮件--- 发件人: "Jianxin @.&gt; 发送时间: 2024年3月29日(周五) 晚上9:03 收件人: @.&gt;; 抄送: @.&gt;; 主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104) function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。 我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？ 是的，都支持。qwen1.5（以及dashscope的qwen-max/plus/turbo) 一般推荐用默认的function calling模版（指examples/function_calling.py那个示例背后用的模版） —— 但这个模版目前也发现了一些已知的问题，比如 code Interpreter 效果相比qwen1的react模版有所下降，容易在没有相关工具时误调用工具等问题。可以先试试1.5的模版，效果不佳就回退用qwen1的模版（react模版）。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 1.5模版见 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的，qwen-agent框架对oai接口进行了二次封装，即使oai接口本身没有function call支持，也能通过qwen-agent的封装得到func call支持。（但非qwen1.5的模型是否会遵循我们写的prompt就是另一回事了。）

**Comment by ye7love7** [comment]
我比较好奇怎么用这个fncall来实现工具调用，执行函数，Example中有吗？之前都直接用singleactagent做



---原始邮件---
发件人: "Jianxin ***@***.***&gt;
发送时间: 2024年3月29日(周五) 晚上10:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104)




  
我翻看了一下代码，如果是本地的qwen，用openai接口启动，会对应到oai的llm，这个llm就继承了basetextchatmodel，又继承自basefncallmodel，也就是说本地模型按照openai接口填入模型配置，都有fncall的方法，对吗？
 …
 ---原始邮件--- 发件人: "Jianxin @.&gt; 发送时间: 2024年3月29日(周五) 晚上9:16 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104) 我也发现了1.5工具调用下降的问题。 请问1.5的模板在哪里？ … ---原始邮件--- 发件人: "Jianxin @.&gt; 发送时间: 2024年3月29日(周五) 晚上9:03 收件人: @.&gt;; 抄送: @.&gt;; 主题: Re: [QwenLM/Qwen-Agent] qwen1.5 系列的大模型都支持这个项目吗？ (Issue #104) function call相关的有做一点相应的对齐。其他的prompts大多是prompt engineering了下，没做太多训练。 我尝试用qwen1.0的function call模版格式测试了几个简单的例子，也能正确返回，qwen1.5是同时支持两种格式吗？推荐使用哪种？ 是的，都支持。qwen1.5（以及dashscope的qwen-max/plus/turbo) 一般推荐用默认的function calling模版（指examples/function_calling.py那个示例背后用的模版） —— 但这个模版目前也发现了一些已知的问题，比如 code Interpreter 效果相比qwen1的react模版有所下降，容易在没有相关工具时误调用工具等问题。可以先试试1.5的模版，效果不佳就回退用qwen1的模版（react模版）。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 1.5模版见 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
是的，qwen-agent框架对oai接口进行了二次封装，即使oai接口本身没有function call支持，也能通过qwen-agent的封装得到func call支持。（但非qwen1.5的模型是否会遵循我们写的prompt就是另一回事了。）

**Comment by JianxinMa** [comment]
> 我比较好奇怎么用这个fncall来实现工具调用，执行函数，Example中有吗？之前都直接用singleactagent做

参考这两个：
- https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py
- https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py
